diplom/Presentation/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using Domain.Models;
using Newtonsoft.Json;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.ViewModel;
using Presentation.Models;

namespace Presentation.Controllers
{
    public class GroupController : Controller
    {
        Uri baseAddress = new Uri("http://192.168.0.105:5183/api");
        private readonly HttpClient _client;

        public GroupController()
        {
            // Настроить HttpClientHandler для извлечения токена из куки
            var handler = new HttpClientHandler();

            // Создать HttpClient с обработчиком
            _client = new HttpClient(handler)
            {
                BaseAddress = baseAddress
            };
        }
        private void AddAuthorizationHeader()
        {
            // Получаем токен из куки
            var token = Request.Cookies["AuthToken"]; // Используйте имя куки для токена

            if (!string.IsNullOrEmpty(token))
            {
                // Добавляем токен в заголовок Authorization
                _client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", token);
            }
        }

        [HttpGet]
        public IActionResult Index(string SearchGroupName, string SearchChiefName, string SearchFacilityName, int? pageNumber)
        {
            AddAuthorizationHeader();
            ViewData["SearchGroupName"] = SearchGroupName;
            ViewData["SearchChiefName"] = SearchChiefName;
            ViewData["SearchFacilityName"] = SearchFacilityName;
            IQueryable<Group> GroupList = null;

            HttpResponseMessage response = _client.GetAsync($"{_client.BaseAddress}/Group/Filter?Name={SearchGroupName}&Chief.Name={SearchChiefName}&Facility.Name={SearchFacilityName}").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                GroupList = JsonConvert.DeserializeObject<List<Group>>(data).AsQueryable();
            }
            else
            {
                // Return an error page with the status code in the ViewModel
                int statusCode = (int)response.StatusCode;
                var errorViewModel = new ErrorViewModel
                {
                    RequestId = $"Error code: {statusCode}"
                };

                return View("Error", errorViewModel);
            }
            int pageSize = 20;

            return View(PaginatedList<Group>.Create(GroupList.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult Create()
        {
            SetViewDataAsync();
            return View();
        }

        [HttpPost]
        public IActionResult Create(GroupViewModel model)
        {
            try
            {
                AddAuthorizationHeader();
                string data = JsonConvert.SerializeObject(model);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Group/Post", content).Result;
                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Group created.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }

            return View();
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                AddAuthorizationHeader();
                GroupViewModel Group = new GroupViewModel();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Group/GetGroup/" + id).Result;
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    Group =  JsonConvert.DeserializeObject<GroupViewModel>(data);
                    SetViewDataAsync(Group.FacilityId, Group.ChiefId);
                }
                return View(Group);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }
        [HttpPost]
        public IActionResult Edit(GroupViewModel Group)
        {
            AddAuthorizationHeader();

            string data = JsonConvert.SerializeObject(Group);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + "/Group/Put", content).Result;
            if (response.IsSuccessStatusCode)
            {
                TempData["successMessage"] = "Group updated.";
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            try
            {
                AddAuthorizationHeader();

                GroupViewModel Group = new GroupViewModel();
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Group/GetGroup/" + id).Result;
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    Group = JsonConvert.DeserializeObject<GroupViewModel>(data);
                    SetViewDataAsync(Group.FacilityId, Group.ChiefId);
                }
                return View(Group);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                AddAuthorizationHeader();

                HttpResponseMessage response = _client.DeleteAsync(_client.BaseAddress + "/Group/Delete/" + id).Result;
                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Group deleted.";
                }
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }

        }
        private void SetViewDataAsync(int? facilityId = null, int? chiefId = null)
        {
            AddAuthorizationHeader();
            List<Facility> facilityList = new List<Facility>();
            HttpResponseMessage response1 = _client.GetAsync(_client.BaseAddress + "/Facility/GetAll").Result;
            if (response1.IsSuccessStatusCode)
            {
                string data = response1.Content.ReadAsStringAsync().Result;
                facilityList = JsonConvert.DeserializeObject<List<Facility>>(data);
            }
            ViewData["FacilityId"] = new SelectList(facilityList, "Id", "Name", facilityId);

            List<Chief> chiefList = new List<Chief>();
            HttpResponseMessage response2 = _client.GetAsync(_client.BaseAddress + "/Chief/GetAll").Result;
            if (response2.IsSuccessStatusCode)
            {
                string data = response2.Content.ReadAsStringAsync().Result;
                chiefList = JsonConvert.DeserializeObject<List<Chief>>(data);
            }
            ViewData["ChiefId"] = new SelectList(chiefList, "Id", "Name", chiefId);
        }
    }
}

diplom/Presentation/Controllers/RolesController.cs
using Domain.Models;
using Domain.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Presentation.Models;
using System.Data;
using System.Text;

namespace Presentation.Controllers
{
    public class RolesController : Controller
    {
        Uri baseAddress = new Uri("http://192.168.0.105:5183/api");
        private readonly HttpClient _client;

        public RolesController()
        {
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        [HttpGet]
        public async Task<IActionResult> UserList(int? pageNumber)
        {
            IQueryable<User> users = null;

            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Roles/UserList").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                users = JsonConvert.DeserializeObject<List<User>>(data).AsQueryable();
            }
            else
            {
                // Return an error page with the status code in the ViewModel
                int statusCode = (int)response.StatusCode;
                var errorViewModel = new ErrorViewModel
                {
                    RequestId = $"Error code: {statusCode}"
                };

                return View("Error", errorViewModel);
            }
            var userRoles = new List<UserWithRoleViewModel>();

            foreach (var user in users)
            {
                HttpResponseMessage response2 = _client.GetAsync(_client.BaseAddress + "/Roles/GetUserRoles?userId=" + user.Id).Result;
                IQueryable<string> roles = null;
                if (response.IsSuccessStatusCode)
                {
                    string data = await response2.Content.ReadAsStringAsync();
                    roles = JsonConvert.DeserializeObject<List<string>>(data).AsQueryable();
                }
                else
                {
                    // Return an error page with the status code in the ViewModel
                    int statusCode = (int)response2.StatusCode;
                    var errorViewModel = new ErrorViewModel
                    {
                        RequestId = $"Error code: {statusCode}"
                    };

                    return View("Error", errorViewModel);
                }
               
                userRoles.Add(new UserWithRoleViewModel
                {
                    Id = user.Id,
                    Username = user.UserName,
                    FullName = $"{user.LastName} {user.FirstName} {user.FatherName}",
                    Role = roles
                });
            }

            int pageSize = 20;
            var paginatedList = PaginatedList<UserWithRoleViewModel>.Create(userRoles.AsQueryable().AsNoTracking(), pageNumber ?? 1, pageSize);

            return View(paginatedList);
        }
        [HttpGet]
        public async Task<IActionResult> RoleList(int? pageNumber)
        {
            IQueryable<Role> RoleList = null;

            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Roles/RoleList").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                RoleList = JsonConvert.DeserializeObject<List<Role>>(data).AsQueryable();
            }
            else
            {
                // Return an error page with the status code in the ViewModel
                int statusCode = (int)response.StatusCode;
                var errorViewModel = new ErrorViewModel
                {
                    RequestId = $"Error code: {statusCode}"
                };

                return View("Error", errorViewModel);
            }
            int pageSize = 20;

            return View(PaginatedList<Role>.Create(RoleList.AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id, List<string> Roles)
        {
            try
            { 
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Roles/RoleList").Result;
                List<Role> roles = new List<Role>();

                if (response.IsSuccessStatusCode)
                {
                    string data = await response.Content.ReadAsStringAsync();
                    roles = JsonConvert.DeserializeObject<List<Role>>(data);
                }
                RoleViewModel viewModel = new RoleViewModel
                {
                    Id = id,
                    RoleList = roles,
                    Roles = Roles
                };
                return View(viewModel);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }
        [HttpPost]
        public async Task<IActionResult> UpdateRoles(RoleViewModel newRoles)
        {
            // Обработка обновленных данных
            // Пример сохранения изменений
            if (newRoles.Roles != null)
            {
                var url = _client.BaseAddress + $"/Roles/Put?userId={newRoles.Id}";

                // Create a list of roles

                // Serialize the list to a JSON string
                var jsonContent = JsonConvert.SerializeObject(newRoles.Roles);

                var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

                var response = await _client.PutAsync(url, content);
                // Логика сохранения выбранных ролей
                if (response.IsSuccessStatusCode)
                {
                    TempData["Success"] = "Roles updated successfully!";
                }
                else
                {
                    TempData["Error"] = "Failed to update roles.";
                }
            }

            return RedirectToAction("UserList");
        }

    }
}

diplom/Presentation/Views/Shared/_Layout.cshtml
@{
    var authToken = Context?.Request?.Cookies["AuthToken"];
    var email = string.Empty;
    var roles = new List<string>(); // Список для хранения ролей
    var isAuthSuccessful = false;

    if (!string.IsNullOrEmpty(authToken))
    {
        var handler = new System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler();
        var jwtToken = handler.ReadJwtToken(authToken);

        // Получение email
        email = jwtToken.Claims.FirstOrDefault(c => c.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name")?.Value;

        // Получение всех ролей
        roles = jwtToken.Claims
            .Where(c => c.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/role")
            .Select(c => c.Value)
            .ToList();

        isAuthSuccessful = true;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Presentation.styles.css" asp-append-version="true" />
    <link href="~/datatables/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Presentation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (roles.Any(r => r != "Chief"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Facility" asp-action="Index">Факультеты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Учителя</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Chief" asp-action="Index">Старосты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Discipline" asp-action="Index">Дисциплины</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Group" asp-action="Index">Группы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Студенты</a>
                            </li>
                        }
                        @if (roles.Any())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Schedule" asp-action="Index">Расписание</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Attendance" asp-action="Index">Посещения</a>
                            </li>
                        }
                        @if (roles.Contains("Dean"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="UserList">Пользователи</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="RoleList">Роли</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @{
                var errorMessage = TempData["errorMessage"]?.ToString();
                var successMessage = TempData["successMessage"]?.ToString();

            }
            @if (!string.IsNullOrWhiteSpace(successMessage))
            {
                <div class="alert alert-success">
                    <b>Success : </b>@successMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            else if(!string.IsNullOrWhiteSpace(errorMessage))
            {
                <div class="alert alert-danger">
                    <b>Error : </b>@errorMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="close"></button>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/datatables/datatables.min.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>